### ISSUE TITLE
Обнаружена уязвимость с возможностью ввода отрицательных значений

### ISSUE THREAD

**Issue by Eraphion** [KonstantinFed/lab6Fed#1]
В приложении под пунктом Create new power app в поле count of points мне удалось ввести отрицательное число, это может привести к некорректной работе приложения. Необходимо контролировать введенное значение. Прилагаю скриншот, подтверждающий проблему.
![image](https://cloud.githubusercontent.com/assets/23791960/26541643/b0912568-4480-11e7-846d-702080a4aca9.png)

**Comment by Eraphion** [comment]
Вот ещё один скриншот, на котором ясно видно, что программа позволила ввести отрицательное значение

**Comment by KonstantinFed** [comment]
Спасибо за тщательное тестирование программы. Доводим до Вашего сведения, что уязвимость исправлена, подобная проблема не должна встретиться в будущем.
С уважением, генеральный главный лидирующий ответственный за разработку Костя
![image](https://cloud.githubusercontent.com/assets/23392551/26542239/6a4439e4-4483-11e7-9011-50ab178a273b.png)

**Comment by Eraphion** [comment]
Довожу до Вашего сведения, что в результате долгой и тщательной проверки нашей командой специалистов не было выявлено внештатных ситуаций, программа не позволяла совершить действия, которые привели бы к нарушению логики работы приложения. Закрываю проблему.
